### ISSUE TITLE
HostData bug

### ISSUE THREAD

**Issue by AdrianLungu** [ns3777k/go-shodan#15]
I've ran into an issue when searching for **argentina** where the results contain a number in the **version** field and Go wants a string.

```
options := shodan.HostQueryOptions{
		Query: query,
	}

results, err := client.GetHostsForQuery(&options)
```

With query = `argentina` results in

> json: cannot unmarshal number into Go struct field HostData.version of type string

Not really sure if this is a bug with the library or with Shodan though.

Thanks!

**Comment by ns3777k** [comment]
Hey, @AdrianLungu! I'll take a look today.

**Comment by ns3777k** [comment]
@AdrianLungu I've just pushed v1.0.1 tag that should fix the issue. Can you check this?
