### ISSUE TITLE
GetServicesForHost fails querying a IPv6 address

### ISSUE THREAD

**Issue by llonchj** [ns3777k/go-shodan#33]
### Issue details and expected behavior

Error: `json: cannot unmarshal string into Go struct field HostData.ip of type int64` calling client.GetServicesForHost("2600:1802:12::1", nil)

It appears that shodan is returning a string in the `ip` field when the IP is a IPV6 address

```

{
"city": null,
"region_code": null,
"os": null,
"tags": [],
"ip": "2600:1802:12::1",
"isp": null,
"area_code": null,
"dma_code": null,
"last_update": "2018-01-23T10:18:14.526523",
...
...
...
...
```

### Environment

1. What `go` version are you using? `go version go1.9.3 darwin/amd64`
2. Are you using the latest `go-shodan` version? yes
3. What OS are you using? OSX

### Minimal reproducible demo
```go

client.GetServicesForHost("2600:1802:12::1", nil)

```

**Comment by ns3777k** [comment]
hey @llonchj ! thanks for the issue i'll take a look soon

**Comment by llonchj** [comment]
I have mitigated the issue by replacing IP data type from int to
interface{}. I will suggest a better solution has to be in place, like a
`func (h *Host) UnmarshalJSON`.


2018-02-02 21:53 GMT+11:00 Nikita Safonov <notifications@github.com>:

**Comment by ns3777k** [comment]
Well.

From what I see, there are two fields coming from the api - `ip` and `ip_str`. There are also duplicated in `HostData` struct. For ipv4 `ip_str` contains a string and `ip` - a number. But in case of ipv6 both those fields contain strings. Example:

```
IP: 2600:1802:12::1
ip field: "2600:1802:12::1" (string)
ip_str field: "2600:1802:12::1" (string)

IP: 8.8.8.8
ip field: 134744072 (int)
ip_str field: "8.8.8.8" (string)
```

Maybe there's no need to unmarshal `ip` that and leave it to the user? Anyway I'll replace string with net.IP.

**Comment by llonchj** [comment]
that's clever! net.IP looks like the fix!

2018-02-03 10:33 GMT+11:00 Nikita Safonov <notifications@github.com>:

**Comment by ns3777k** [comment]
https://github.com/ns3777k/go-shodan/pull/34

**Comment by ns3777k** [comment]
Merged. `ip` removed, `ip_str` is not `net.IP`. @llonchj can you give it a test?

**Comment by llonchj** [comment]
It works. Thank you @ns3777k!

2018-02-04 9:40 GMT+11:00 Nikita Safonov <notifications@github.com>:

**Comment by ns3777k** [comment]
Ok. Closing this :+1:
