### ISSUE TITLE
Hostdata Struct Modification to support SSL Info

### ISSUE THREAD

**Issue by ericlfisher** [ns3777k/go-shodan#41]
### Issue details and expected behavior

Currently, unless I'm missing something, the results returned for a GetHostsForQuery call don't return any SSL banners, even though the SSL info is now a top-level property as per https://blog.shodan.io/ssl-update/

Could the HostData struct be modified to support this?

### Environment

1. What `go` version are you using? 1.10
2. Are you using the latest `go-shodan` version? yes
3. What OS are you using? OSX 10.13.4

### Minimal reproducible demo

```go
// you code here
```

**Comment by ns3777k** [comment]
Hey! Thanks for the issue, I'll take a look today

**Comment by ns3777k** [comment]
Yup, you're right! I'll add ssl prop to struct today

**Comment by ericlfisher** [comment]
Awesome, thanks

**Comment by ns3777k** [comment]
Well, I added some structs to support ssl here https://github.com/ns3777k/go-shodan/pull/42/. But a little refactoring is still needed with some tests. I'll finally get done with it tomorrow or later this week.

@ericlfisher appreciate it if you find some time to test the branch for any weird panics 'cause shodan sometimes replies with really unexpected data types -_-

**Comment by ns3777k** [comment]
@ericlfisher I fixed it a bit and pushed under v3.1.0 tag. you're now able to "repull" v3 version to get it.

**Comment by ericlfisher** [comment]
Awesome, thanks
