### ISSUE TITLE
i swear we read the same book

### ISSUE THREAD

**Issue by ArkAngeL43** [ns3777k/go-shodan#62]
im cureious about this and sorry if its a waste of time but is this built off of the Black Hat GO book, they have a section that looks exactly like this accept you made it 1000000000000000 times better XDDD

**Comment by ns3777k** [comment]
Hey @ArkAngeL43 !
I saw that book but didn't read it. The code in this repository was pushed years before the book got published 😄 (book's year - 2020, repository's year - 2017-2018)
Structs can be identical indeed as well as http interaction, 'cause that's a simple http client, very straightforward. The devil is in the details 😄 
Thanks for the feedback 😄
